### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by SylvainCorlay** [bollwyvl/cookiecutter-ipython-widget#3]
Some people at the PyData tutorial I gave tried this one instead of the official jupyter cookiecutter and this caused some confusion.

Would you be ok deprecating or removing that repo since we released the one of the jupyter org?

**Comment by bollwyvl** [comment]
I'm on it!

**Comment by bollwyvl** [comment]
Updated README... reasonable enough? I don't like to kill repos off that others have worked on as a general priniciple.

**Comment by SylvainCorlay** [comment]
Thanks! (I thought there was only a few commits ahead of Audrey Roy's pip example)
